kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  namespace: jenkins
spec:
  replicas: 1
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: app
      # version: v01
  template:
    metadata:
      labels:
        app: app
        # version: v01
    spec:
      containers:
      - name: test1
        image: httpd
        ports:
        - containerPort: 80
